// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Resource struct {
	ID          string    `json:"id"`
	Kind        string    `json:"kind"`
	Version     string    `json:"version"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Spec        []byte    `json:"spec"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TestExecution struct {
	ID                   string         `json:"id"`
	TestSuiteExecutionID sql.NullString `json:"test_suite_execution_id"`
	StartedAt            time.Time      `json:"started_at"`
	FinishedAt           time.Time      `json:"finished_at"`
	Status               string         `json:"status"`
	EnvironmentID        string         `json:"environment_id"`
	EnvironmentName      string         `json:"environment_name"`
	TestID               string         `json:"test_id"`
	TestName             string         `json:"test_name"`
	Summary              []byte         `json:"summary"`
}

type TestSuiteExecution struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	Summary         []byte    `json:"summary"`
}

type TestTag struct {
	TestID string `json:"test_id"`
	Tag    string `json:"tag"`
}
