// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// resources.sql
	// ============================================================================
	// CRUD
	// ============================================================================
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	// ============================================================================
	// CRUD
	// ============================================================================
	CreateTestExecution(ctx context.Context, arg CreateTestExecutionParams) (TestExecution, error)
	// ============================================================================
	// CRUD
	// ============================================================================
	CreateTestSuiteExecution(ctx context.Context, arg CreateTestSuiteExecutionParams) (TestSuiteExecution, error)
	CreateTestTag(ctx context.Context, arg CreateTestTagParams) error
	DeleteResource(ctx context.Context, arg DeleteResourceParams) (Resource, error)
	DeleteTestExecution(ctx context.Context, id string) (TestExecution, error)
	DeleteTestSuiteExecution(ctx context.Context, id string) (TestSuiteExecution, error)
	DeleteTestTagsByTestID(ctx context.Context, testID string) error
	GetResource(ctx context.Context, arg GetResourceParams) (Resource, error)
	// ============================================================================
	// Prefix lookup
	// ============================================================================
	GetResourceIDsByID(ctx context.Context, arg GetResourceIDsByIDParams) ([]string, error)
	GetResourceIDsByName(ctx context.Context, arg GetResourceIDsByNameParams) ([]string, error)
	GetTestExecution(ctx context.Context, id string) (TestExecution, error)
	// ============================================================================
	// Prefix lookup
	// ============================================================================
	GetTestExecutionIDsByID(ctx context.Context, prefix sql.NullString) ([]string, error)
	// ============================================================================
	// Parent lookup
	// ============================================================================
	GetTestExecutionIDsByTestSuiteExecutionID(ctx context.Context, testSuiteExecutionID sql.NullString) ([]string, error)
	// ============================================================================
	// Status
	// ============================================================================
	GetTestExecutionStatus(ctx context.Context, id string) (string, error)
	GetTestExecutionsByTestSuiteExecutionID(ctx context.Context, testSuiteExecutionID string) ([]TestExecution, error)
	GetTestSuiteExecution(ctx context.Context, id string) (GetTestSuiteExecutionRow, error)
	// ============================================================================
	// Prefix lookup
	// ============================================================================
	GetTestSuiteExecutionIDsByID(ctx context.Context, prefix sql.NullString) ([]string, error)
	GetTestSuiteExecutionIDsByTestSuiteID(ctx context.Context, prefix sql.NullString) ([]string, error)
	// ============================================================================
	// Status
	// ============================================================================
	GetTestSuiteExecutionStatus(ctx context.Context, id string) (string, error)
	GetTestsByTag(ctx context.Context, tag string) ([]Resource, error)
	// ============================================================================
	// Cursor page: CreatedAt
	// ============================================================================
	ListResourcesByCreatedAtAfterAsc(ctx context.Context, arg ListResourcesByCreatedAtAfterAscParams) ([]Resource, error)
	ListResourcesByCreatedAtAfterDesc(ctx context.Context, arg ListResourcesByCreatedAtAfterDescParams) ([]Resource, error)
	ListResourcesByCreatedAtBeforeAsc(ctx context.Context, arg ListResourcesByCreatedAtBeforeAscParams) ([]Resource, error)
	ListResourcesByCreatedAtBeforeDesc(ctx context.Context, arg ListResourcesByCreatedAtBeforeDescParams) ([]Resource, error)
	// ============================================================================
	// First page: CreatedAt
	// ============================================================================
	ListResourcesByCreatedAtFirstAsc(ctx context.Context, arg ListResourcesByCreatedAtFirstAscParams) ([]Resource, error)
	ListResourcesByCreatedAtFirstDesc(ctx context.Context, arg ListResourcesByCreatedAtFirstDescParams) ([]Resource, error)
	// ============================================================================
	// Cursor page: ID
	// ============================================================================
	ListResourcesByIDAfterAsc(ctx context.Context, arg ListResourcesByIDAfterAscParams) ([]Resource, error)
	ListResourcesByIDAfterDesc(ctx context.Context, arg ListResourcesByIDAfterDescParams) ([]Resource, error)
	ListResourcesByIDBeforeAsc(ctx context.Context, arg ListResourcesByIDBeforeAscParams) ([]Resource, error)
	ListResourcesByIDBeforeDesc(ctx context.Context, arg ListResourcesByIDBeforeDescParams) ([]Resource, error)
	// ============================================================================
	// First page: ID
	// ============================================================================
	ListResourcesByIDFirstAsc(ctx context.Context, arg ListResourcesByIDFirstAscParams) ([]Resource, error)
	ListResourcesByIDFirstDesc(ctx context.Context, arg ListResourcesByIDFirstDescParams) ([]Resource, error)
	// ============================================================================
	// Cursor page: Name
	// ============================================================================
	ListResourcesByNameAfterAsc(ctx context.Context, arg ListResourcesByNameAfterAscParams) ([]Resource, error)
	ListResourcesByNameAfterDesc(ctx context.Context, arg ListResourcesByNameAfterDescParams) ([]Resource, error)
	ListResourcesByNameBeforeAsc(ctx context.Context, arg ListResourcesByNameBeforeAscParams) ([]Resource, error)
	ListResourcesByNameBeforeDesc(ctx context.Context, arg ListResourcesByNameBeforeDescParams) ([]Resource, error)
	// ============================================================================
	// First page: Name
	// ============================================================================
	ListResourcesByNameFirstAsc(ctx context.Context, arg ListResourcesByNameFirstAscParams) ([]Resource, error)
	ListResourcesByNameFirstDesc(ctx context.Context, arg ListResourcesByNameFirstDescParams) ([]Resource, error)
	// ============================================================================
	// Cursor page: UpdatedAt
	// ============================================================================
	ListResourcesByUpdatedAtAfterAsc(ctx context.Context, arg ListResourcesByUpdatedAtAfterAscParams) ([]Resource, error)
	ListResourcesByUpdatedAtAfterDesc(ctx context.Context, arg ListResourcesByUpdatedAtAfterDescParams) ([]Resource, error)
	ListResourcesByUpdatedAtBeforeAsc(ctx context.Context, arg ListResourcesByUpdatedAtBeforeAscParams) ([]Resource, error)
	ListResourcesByUpdatedAtBeforeDesc(ctx context.Context, arg ListResourcesByUpdatedAtBeforeDescParams) ([]Resource, error)
	// ============================================================================
	// First page: UpdatedAt
	// ============================================================================
	ListResourcesByUpdatedAtFirstAsc(ctx context.Context, arg ListResourcesByUpdatedAtFirstAscParams) ([]Resource, error)
	ListResourcesByUpdatedAtFirstDesc(ctx context.Context, arg ListResourcesByUpdatedAtFirstDescParams) ([]Resource, error)
	// ============================================================================
	// Cursor page: Version
	// ============================================================================
	ListResourcesByVersionAfterAsc(ctx context.Context, arg ListResourcesByVersionAfterAscParams) ([]Resource, error)
	ListResourcesByVersionAfterDesc(ctx context.Context, arg ListResourcesByVersionAfterDescParams) ([]Resource, error)
	ListResourcesByVersionBeforeAsc(ctx context.Context, arg ListResourcesByVersionBeforeAscParams) ([]Resource, error)
	ListResourcesByVersionBeforeDesc(ctx context.Context, arg ListResourcesByVersionBeforeDescParams) ([]Resource, error)
	// ============================================================================
	// First page: Version
	// ============================================================================
	ListResourcesByVersionFirstAsc(ctx context.Context, arg ListResourcesByVersionFirstAscParams) ([]Resource, error)
	ListResourcesByVersionFirstDesc(ctx context.Context, arg ListResourcesByVersionFirstDescParams) ([]Resource, error)
	// ============================================================================
	// Cursor page: FinishedAt
	// ============================================================================
	// PositionAfter + ASC
	ListTestExecutionsByFinishedAtAfterAsc(ctx context.Context, arg ListTestExecutionsByFinishedAtAfterAscParams) ([]TestExecution, error)
	// PositionAfter + DESC
	ListTestExecutionsByFinishedAtAfterDesc(ctx context.Context, arg ListTestExecutionsByFinishedAtAfterDescParams) ([]TestExecution, error)
	// PositionBefore + ASC
	// Results are queried in reverse order.
	// The repository must restore ASC order.
	ListTestExecutionsByFinishedAtBeforeAsc(ctx context.Context, arg ListTestExecutionsByFinishedAtBeforeAscParams) ([]TestExecution, error)
	// PositionBefore + DESC
	// Results are queried in reverse order.
	// The repository must restore DESC order.
	ListTestExecutionsByFinishedAtBeforeDesc(ctx context.Context, arg ListTestExecutionsByFinishedAtBeforeDescParams) ([]TestExecution, error)
	// ============================================================================
	// First page: FinishedAt
	// ============================================================================
	ListTestExecutionsByFinishedAtFirstAsc(ctx context.Context, pageLimit int64) ([]TestExecution, error)
	ListTestExecutionsByFinishedAtFirstDesc(ctx context.Context, pageLimit int64) ([]TestExecution, error)
	// ============================================================================
	// Cursor page: ID
	// ============================================================================
	// PositionAfter + ASC
	ListTestExecutionsByIDAfterAsc(ctx context.Context, arg ListTestExecutionsByIDAfterAscParams) ([]TestExecution, error)
	// PositionAfter + DESC
	ListTestExecutionsByIDAfterDesc(ctx context.Context, arg ListTestExecutionsByIDAfterDescParams) ([]TestExecution, error)
	// PositionBefore + ASC
	// Results are queried in reverse order.
	// The repository must restore ASC order.
	ListTestExecutionsByIDBeforeAsc(ctx context.Context, arg ListTestExecutionsByIDBeforeAscParams) ([]TestExecution, error)
	// PositionBefore + DESC
	// Results are queried in reverse order.
	// The repository must restore DESC order.
	ListTestExecutionsByIDBeforeDesc(ctx context.Context, arg ListTestExecutionsByIDBeforeDescParams) ([]TestExecution, error)
	// ============================================================================
	// First page: ID
	// ============================================================================
	ListTestExecutionsByIDFirstAsc(ctx context.Context, pageLimit int64) ([]TestExecution, error)
	ListTestExecutionsByIDFirstDesc(ctx context.Context, pageLimit int64) ([]TestExecution, error)
	// ============================================================================
	// Cursor page: StartedAt
	// ============================================================================
	// PositionAfter + ASC
	ListTestExecutionsByStartedAtAfterAsc(ctx context.Context, arg ListTestExecutionsByStartedAtAfterAscParams) ([]TestExecution, error)
	// PositionAfter + DESC
	ListTestExecutionsByStartedAtAfterDesc(ctx context.Context, arg ListTestExecutionsByStartedAtAfterDescParams) ([]TestExecution, error)
	// PositionBefore + ASC
	// Results are queried in reverse order.
	// The repository must restore ASC order.
	ListTestExecutionsByStartedAtBeforeAsc(ctx context.Context, arg ListTestExecutionsByStartedAtBeforeAscParams) ([]TestExecution, error)
	// PositionBefore + DESC
	// Results are queried in reverse order.
	// The repository must restore DESC order.
	ListTestExecutionsByStartedAtBeforeDesc(ctx context.Context, arg ListTestExecutionsByStartedAtBeforeDescParams) ([]TestExecution, error)
	// ============================================================================
	// First page: StartedAt
	// ============================================================================
	ListTestExecutionsByStartedAtFirstAsc(ctx context.Context, pageLimit int64) ([]TestExecution, error)
	ListTestExecutionsByStartedAtFirstDesc(ctx context.Context, pageLimit int64) ([]TestExecution, error)
	// ============================================================================
	// Cursor page: Status
	// ============================================================================
	// PositionAfter + ASC
	ListTestExecutionsByStatusAfterAsc(ctx context.Context, arg ListTestExecutionsByStatusAfterAscParams) ([]TestExecution, error)
	// PositionAfter + DESC
	ListTestExecutionsByStatusAfterDesc(ctx context.Context, arg ListTestExecutionsByStatusAfterDescParams) ([]TestExecution, error)
	// PositionBefore + ASC
	// Results are queried in reverse order.
	// The repository must restore ASC order.
	ListTestExecutionsByStatusBeforeAsc(ctx context.Context, arg ListTestExecutionsByStatusBeforeAscParams) ([]TestExecution, error)
	// PositionBefore + DESC
	// Results are queried in reverse order.
	// The repository must restore DESC order.
	ListTestExecutionsByStatusBeforeDesc(ctx context.Context, arg ListTestExecutionsByStatusBeforeDescParams) ([]TestExecution, error)
	// ============================================================================
	// First page: Status
	// ============================================================================
	ListTestExecutionsByStatusFirstAsc(ctx context.Context, pageLimit int64) ([]TestExecution, error)
	ListTestExecutionsByStatusFirstDesc(ctx context.Context, pageLimit int64) ([]TestExecution, error)
	// ============================================================================
	// Cursor page: FinishedAt
	// ============================================================================
	ListTestSuiteExecutionsByFinishedAtAfterAsc(ctx context.Context, arg ListTestSuiteExecutionsByFinishedAtAfterAscParams) ([]ListTestSuiteExecutionsByFinishedAtAfterAscRow, error)
	ListTestSuiteExecutionsByFinishedAtAfterDesc(ctx context.Context, arg ListTestSuiteExecutionsByFinishedAtAfterDescParams) ([]ListTestSuiteExecutionsByFinishedAtAfterDescRow, error)
	ListTestSuiteExecutionsByFinishedAtBeforeAsc(ctx context.Context, arg ListTestSuiteExecutionsByFinishedAtBeforeAscParams) ([]ListTestSuiteExecutionsByFinishedAtBeforeAscRow, error)
	ListTestSuiteExecutionsByFinishedAtBeforeDesc(ctx context.Context, arg ListTestSuiteExecutionsByFinishedAtBeforeDescParams) ([]ListTestSuiteExecutionsByFinishedAtBeforeDescRow, error)
	// ============================================================================
	// First page: FinishedAt
	// ============================================================================
	ListTestSuiteExecutionsByFinishedAtFirstAsc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByFinishedAtFirstAscRow, error)
	ListTestSuiteExecutionsByFinishedAtFirstDesc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByFinishedAtFirstDescRow, error)
	// ============================================================================
	// Cursor page: ID
	// ============================================================================
	ListTestSuiteExecutionsByIDAfterAsc(ctx context.Context, arg ListTestSuiteExecutionsByIDAfterAscParams) ([]ListTestSuiteExecutionsByIDAfterAscRow, error)
	ListTestSuiteExecutionsByIDAfterDesc(ctx context.Context, arg ListTestSuiteExecutionsByIDAfterDescParams) ([]ListTestSuiteExecutionsByIDAfterDescRow, error)
	ListTestSuiteExecutionsByIDBeforeAsc(ctx context.Context, arg ListTestSuiteExecutionsByIDBeforeAscParams) ([]ListTestSuiteExecutionsByIDBeforeAscRow, error)
	ListTestSuiteExecutionsByIDBeforeDesc(ctx context.Context, arg ListTestSuiteExecutionsByIDBeforeDescParams) ([]ListTestSuiteExecutionsByIDBeforeDescRow, error)
	// ============================================================================
	// First page: ID
	// ============================================================================
	ListTestSuiteExecutionsByIDFirstAsc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByIDFirstAscRow, error)
	ListTestSuiteExecutionsByIDFirstDesc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByIDFirstDescRow, error)
	// ============================================================================
	// Cursor page: StartedAt
	// ============================================================================
	ListTestSuiteExecutionsByStartedAtAfterAsc(ctx context.Context, arg ListTestSuiteExecutionsByStartedAtAfterAscParams) ([]ListTestSuiteExecutionsByStartedAtAfterAscRow, error)
	ListTestSuiteExecutionsByStartedAtAfterDesc(ctx context.Context, arg ListTestSuiteExecutionsByStartedAtAfterDescParams) ([]ListTestSuiteExecutionsByStartedAtAfterDescRow, error)
	ListTestSuiteExecutionsByStartedAtBeforeAsc(ctx context.Context, arg ListTestSuiteExecutionsByStartedAtBeforeAscParams) ([]ListTestSuiteExecutionsByStartedAtBeforeAscRow, error)
	ListTestSuiteExecutionsByStartedAtBeforeDesc(ctx context.Context, arg ListTestSuiteExecutionsByStartedAtBeforeDescParams) ([]ListTestSuiteExecutionsByStartedAtBeforeDescRow, error)
	// ============================================================================
	// First page: StartedAt
	// ============================================================================
	ListTestSuiteExecutionsByStartedAtFirstAsc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByStartedAtFirstAscRow, error)
	ListTestSuiteExecutionsByStartedAtFirstDesc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByStartedAtFirstDescRow, error)
	// ============================================================================
	// Cursor page: Status
	// ============================================================================
	ListTestSuiteExecutionsByStatusAfterAsc(ctx context.Context, arg ListTestSuiteExecutionsByStatusAfterAscParams) ([]ListTestSuiteExecutionsByStatusAfterAscRow, error)
	ListTestSuiteExecutionsByStatusAfterDesc(ctx context.Context, arg ListTestSuiteExecutionsByStatusAfterDescParams) ([]ListTestSuiteExecutionsByStatusAfterDescRow, error)
	ListTestSuiteExecutionsByStatusBeforeAsc(ctx context.Context, arg ListTestSuiteExecutionsByStatusBeforeAscParams) ([]ListTestSuiteExecutionsByStatusBeforeAscRow, error)
	ListTestSuiteExecutionsByStatusBeforeDesc(ctx context.Context, arg ListTestSuiteExecutionsByStatusBeforeDescParams) ([]ListTestSuiteExecutionsByStatusBeforeDescRow, error)
	// ============================================================================
	// First page: Status
	// ============================================================================
	ListTestSuiteExecutionsByStatusFirstAsc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByStatusFirstAscRow, error)
	ListTestSuiteExecutionsByStatusFirstDesc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByStatusFirstDescRow, error)
	SetTestExecutionCompleted(ctx context.Context, arg SetTestExecutionCompletedParams) (string, error)
	// ============================================================================
	// State transitions
	// ============================================================================
	SetTestExecutionRunning(ctx context.Context, arg SetTestExecutionRunningParams) (string, error)
	SetTestSuiteExecutionCompleted(ctx context.Context, arg SetTestSuiteExecutionCompletedParams) (string, error)
	// ============================================================================
	// State transitions
	// ============================================================================
	SetTestSuiteExecutionRunning(ctx context.Context, arg SetTestSuiteExecutionRunningParams) (string, error)
}

var _ Querier = (*Queries)(nil)
