// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createResource = `-- name: CreateResource :one


INSERT INTO resources (
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
)
VALUES (
           ?1,
           ?2,
           ?3,
           ?4,
           ?5,
           ?6,
           ?7,
           ?8
       )
    RETURNING
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
`

type CreateResourceParams struct {
	ID          string    `json:"id"`
	Kind        string    `json:"kind"`
	Version     string    `json:"version"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Spec        []byte    `json:"spec"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// resources.sql
// ============================================================================
// CRUD
// ============================================================================
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.ID,
		arg.Kind,
		arg.Version,
		arg.Name,
		arg.Description,
		arg.Spec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :one
DELETE FROM resources
WHERE kind = ?1
  AND id = ?2
    RETURNING
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
`

type DeleteResourceParams struct {
	Kind string `json:"kind"`
	ID   string `json:"id"`
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, deleteResource, arg.Kind, arg.ID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND id = ?2
`

type GetResourceParams struct {
	Kind string `json:"kind"`
	ID   string `json:"id"`
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, arg.Kind, arg.ID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceIDsByID = `-- name: GetResourceIDsByID :many

SELECT id
FROM resources
WHERE kind = ?1
  AND id LIKE ?2 || '%'
ORDER BY id ASC
`

type GetResourceIDsByIDParams struct {
	Kind   string         `json:"kind"`
	Prefix sql.NullString `json:"prefix"`
}

// ============================================================================
// Prefix lookup
// ============================================================================
func (q *Queries) GetResourceIDsByID(ctx context.Context, arg GetResourceIDsByIDParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getResourceIDsByID, arg.Kind, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceIDsByName = `-- name: GetResourceIDsByName :many
SELECT id
FROM resources
WHERE kind = ?1
  AND name LIKE ?2 || '%'
ORDER BY name ASC, id ASC
`

type GetResourceIDsByNameParams struct {
	Kind   string         `json:"kind"`
	Prefix sql.NullString `json:"prefix"`
}

func (q *Queries) GetResourceIDsByName(ctx context.Context, arg GetResourceIDsByNameParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getResourceIDsByName, arg.Kind, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCreatedAtAfterAsc = `-- name: ListResourcesByCreatedAtAfterAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (created_at, id) >
      (?2, CAST(?3 AS TEXT))
ORDER BY created_at ASC, id ASC
    LIMIT ?4
`

type ListResourcesByCreatedAtAfterAscParams struct {
	Kind            string    `json:"kind"`
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// ============================================================================
// Cursor page: CreatedAt
// ============================================================================
func (q *Queries) ListResourcesByCreatedAtAfterAsc(ctx context.Context, arg ListResourcesByCreatedAtAfterAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCreatedAtAfterAsc,
		arg.Kind,
		arg.AnchorTimestamp,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCreatedAtAfterDesc = `-- name: ListResourcesByCreatedAtAfterDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (created_at, id) <
      (?2, CAST(?3 AS TEXT))
ORDER BY created_at DESC, id DESC
    LIMIT ?4
`

type ListResourcesByCreatedAtAfterDescParams struct {
	Kind            string    `json:"kind"`
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

func (q *Queries) ListResourcesByCreatedAtAfterDesc(ctx context.Context, arg ListResourcesByCreatedAtAfterDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCreatedAtAfterDesc,
		arg.Kind,
		arg.AnchorTimestamp,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCreatedAtBeforeAsc = `-- name: ListResourcesByCreatedAtBeforeAsc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (created_at, id) <
      (?2, CAST(?3 AS TEXT))
ORDER BY created_at DESC, id DESC
    LIMIT ?4
`

type ListResourcesByCreatedAtBeforeAscParams struct {
	Kind            string    `json:"kind"`
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

func (q *Queries) ListResourcesByCreatedAtBeforeAsc(ctx context.Context, arg ListResourcesByCreatedAtBeforeAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCreatedAtBeforeAsc,
		arg.Kind,
		arg.AnchorTimestamp,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCreatedAtBeforeDesc = `-- name: ListResourcesByCreatedAtBeforeDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (created_at, id) >
      (?2, CAST(?3 AS TEXT))
ORDER BY created_at ASC, id ASC
    LIMIT ?4
`

type ListResourcesByCreatedAtBeforeDescParams struct {
	Kind            string    `json:"kind"`
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

func (q *Queries) ListResourcesByCreatedAtBeforeDesc(ctx context.Context, arg ListResourcesByCreatedAtBeforeDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCreatedAtBeforeDesc,
		arg.Kind,
		arg.AnchorTimestamp,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCreatedAtFirstAsc = `-- name: ListResourcesByCreatedAtFirstAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY created_at ASC, id ASC
    LIMIT ?2
`

type ListResourcesByCreatedAtFirstAscParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

// ============================================================================
// First page: CreatedAt
// ============================================================================
func (q *Queries) ListResourcesByCreatedAtFirstAsc(ctx context.Context, arg ListResourcesByCreatedAtFirstAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCreatedAtFirstAsc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByCreatedAtFirstDesc = `-- name: ListResourcesByCreatedAtFirstDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY created_at DESC, id DESC
    LIMIT ?2
`

type ListResourcesByCreatedAtFirstDescParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByCreatedAtFirstDesc(ctx context.Context, arg ListResourcesByCreatedAtFirstDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByCreatedAtFirstDesc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByIDAfterAsc = `-- name: ListResourcesByIDAfterAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND id > CAST(?2 AS TEXT)
ORDER BY id ASC
    LIMIT ?3
`

type ListResourcesByIDAfterAscParams struct {
	Kind      string `json:"kind"`
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

// ============================================================================
// Cursor page: ID
// ============================================================================
func (q *Queries) ListResourcesByIDAfterAsc(ctx context.Context, arg ListResourcesByIDAfterAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByIDAfterAsc, arg.Kind, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByIDAfterDesc = `-- name: ListResourcesByIDAfterDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND id < CAST(?2 AS TEXT)
ORDER BY id DESC
    LIMIT ?3
`

type ListResourcesByIDAfterDescParams struct {
	Kind      string `json:"kind"`
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByIDAfterDesc(ctx context.Context, arg ListResourcesByIDAfterDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByIDAfterDesc, arg.Kind, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByIDBeforeAsc = `-- name: ListResourcesByIDBeforeAsc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND id < CAST(?2 AS TEXT)
ORDER BY id DESC
    LIMIT ?3
`

type ListResourcesByIDBeforeAscParams struct {
	Kind      string `json:"kind"`
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByIDBeforeAsc(ctx context.Context, arg ListResourcesByIDBeforeAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByIDBeforeAsc, arg.Kind, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByIDBeforeDesc = `-- name: ListResourcesByIDBeforeDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND id > CAST(?2 AS TEXT)
ORDER BY id ASC
    LIMIT ?3
`

type ListResourcesByIDBeforeDescParams struct {
	Kind      string `json:"kind"`
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByIDBeforeDesc(ctx context.Context, arg ListResourcesByIDBeforeDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByIDBeforeDesc, arg.Kind, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByIDFirstAsc = `-- name: ListResourcesByIDFirstAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY id ASC
    LIMIT ?2
`

type ListResourcesByIDFirstAscParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

// ============================================================================
// First page: ID
// ============================================================================
func (q *Queries) ListResourcesByIDFirstAsc(ctx context.Context, arg ListResourcesByIDFirstAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByIDFirstAsc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByIDFirstDesc = `-- name: ListResourcesByIDFirstDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY id DESC
    LIMIT ?2
`

type ListResourcesByIDFirstDescParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByIDFirstDesc(ctx context.Context, arg ListResourcesByIDFirstDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByIDFirstDesc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByNameAfterAsc = `-- name: ListResourcesByNameAfterAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (name, id) >
      (?2, CAST(?3 AS TEXT))
ORDER BY name ASC, id ASC
    LIMIT ?4
`

type ListResourcesByNameAfterAscParams struct {
	Kind        string `json:"kind"`
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

// ============================================================================
// Cursor page: Name
// ============================================================================
func (q *Queries) ListResourcesByNameAfterAsc(ctx context.Context, arg ListResourcesByNameAfterAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByNameAfterAsc,
		arg.Kind,
		arg.AnchorValue,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByNameAfterDesc = `-- name: ListResourcesByNameAfterDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (name, id) <
      (?2, CAST(?3 AS TEXT))
ORDER BY name DESC, id DESC
    LIMIT ?4
`

type ListResourcesByNameAfterDescParams struct {
	Kind        string `json:"kind"`
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByNameAfterDesc(ctx context.Context, arg ListResourcesByNameAfterDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByNameAfterDesc,
		arg.Kind,
		arg.AnchorValue,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByNameBeforeAsc = `-- name: ListResourcesByNameBeforeAsc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (name, id) <
      (?2, CAST(?3 AS TEXT))
ORDER BY name DESC, id DESC
    LIMIT ?4
`

type ListResourcesByNameBeforeAscParams struct {
	Kind        string `json:"kind"`
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByNameBeforeAsc(ctx context.Context, arg ListResourcesByNameBeforeAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByNameBeforeAsc,
		arg.Kind,
		arg.AnchorValue,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByNameBeforeDesc = `-- name: ListResourcesByNameBeforeDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (name, id) >
      (?2, CAST(?3 AS TEXT))
ORDER BY name ASC, id ASC
    LIMIT ?4
`

type ListResourcesByNameBeforeDescParams struct {
	Kind        string `json:"kind"`
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByNameBeforeDesc(ctx context.Context, arg ListResourcesByNameBeforeDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByNameBeforeDesc,
		arg.Kind,
		arg.AnchorValue,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByNameFirstAsc = `-- name: ListResourcesByNameFirstAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY name ASC, id ASC
    LIMIT ?2
`

type ListResourcesByNameFirstAscParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

// ============================================================================
// First page: Name
// ============================================================================
func (q *Queries) ListResourcesByNameFirstAsc(ctx context.Context, arg ListResourcesByNameFirstAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByNameFirstAsc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByNameFirstDesc = `-- name: ListResourcesByNameFirstDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY name DESC, id DESC
    LIMIT ?2
`

type ListResourcesByNameFirstDescParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByNameFirstDesc(ctx context.Context, arg ListResourcesByNameFirstDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByNameFirstDesc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUpdatedAtAfterAsc = `-- name: ListResourcesByUpdatedAtAfterAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (updated_at, id) >
      (?2, CAST(?3 AS TEXT))
ORDER BY updated_at ASC, id ASC
    LIMIT ?4
`

type ListResourcesByUpdatedAtAfterAscParams struct {
	Kind            string    `json:"kind"`
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// ============================================================================
// Cursor page: UpdatedAt
// ============================================================================
func (q *Queries) ListResourcesByUpdatedAtAfterAsc(ctx context.Context, arg ListResourcesByUpdatedAtAfterAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUpdatedAtAfterAsc,
		arg.Kind,
		arg.AnchorTimestamp,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUpdatedAtAfterDesc = `-- name: ListResourcesByUpdatedAtAfterDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (updated_at, id) <
      (?2, CAST(?3 AS TEXT))
ORDER BY updated_at DESC, id DESC
    LIMIT ?4
`

type ListResourcesByUpdatedAtAfterDescParams struct {
	Kind            string    `json:"kind"`
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

func (q *Queries) ListResourcesByUpdatedAtAfterDesc(ctx context.Context, arg ListResourcesByUpdatedAtAfterDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUpdatedAtAfterDesc,
		arg.Kind,
		arg.AnchorTimestamp,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUpdatedAtBeforeAsc = `-- name: ListResourcesByUpdatedAtBeforeAsc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (updated_at, id) <
      (?2, CAST(?3 AS TEXT))
ORDER BY updated_at DESC, id DESC
    LIMIT ?4
`

type ListResourcesByUpdatedAtBeforeAscParams struct {
	Kind            string    `json:"kind"`
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

func (q *Queries) ListResourcesByUpdatedAtBeforeAsc(ctx context.Context, arg ListResourcesByUpdatedAtBeforeAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUpdatedAtBeforeAsc,
		arg.Kind,
		arg.AnchorTimestamp,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUpdatedAtBeforeDesc = `-- name: ListResourcesByUpdatedAtBeforeDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (updated_at, id) >
      (?2, CAST(?3 AS TEXT))
ORDER BY updated_at ASC, id ASC
    LIMIT ?4
`

type ListResourcesByUpdatedAtBeforeDescParams struct {
	Kind            string    `json:"kind"`
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

func (q *Queries) ListResourcesByUpdatedAtBeforeDesc(ctx context.Context, arg ListResourcesByUpdatedAtBeforeDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUpdatedAtBeforeDesc,
		arg.Kind,
		arg.AnchorTimestamp,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUpdatedAtFirstAsc = `-- name: ListResourcesByUpdatedAtFirstAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY updated_at ASC, id ASC
    LIMIT ?2
`

type ListResourcesByUpdatedAtFirstAscParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

// ============================================================================
// First page: UpdatedAt
// ============================================================================
func (q *Queries) ListResourcesByUpdatedAtFirstAsc(ctx context.Context, arg ListResourcesByUpdatedAtFirstAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUpdatedAtFirstAsc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByUpdatedAtFirstDesc = `-- name: ListResourcesByUpdatedAtFirstDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY updated_at DESC, id DESC
    LIMIT ?2
`

type ListResourcesByUpdatedAtFirstDescParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByUpdatedAtFirstDesc(ctx context.Context, arg ListResourcesByUpdatedAtFirstDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByUpdatedAtFirstDesc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByVersionAfterAsc = `-- name: ListResourcesByVersionAfterAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (version, id) >
      (?2, CAST(?3 AS TEXT))
ORDER BY version ASC, id ASC
    LIMIT ?4
`

type ListResourcesByVersionAfterAscParams struct {
	Kind        string `json:"kind"`
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

// ============================================================================
// Cursor page: Version
// ============================================================================
func (q *Queries) ListResourcesByVersionAfterAsc(ctx context.Context, arg ListResourcesByVersionAfterAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByVersionAfterAsc,
		arg.Kind,
		arg.AnchorValue,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByVersionAfterDesc = `-- name: ListResourcesByVersionAfterDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (version, id) <
      (?2, CAST(?3 AS TEXT))
ORDER BY version DESC, id DESC
    LIMIT ?4
`

type ListResourcesByVersionAfterDescParams struct {
	Kind        string `json:"kind"`
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByVersionAfterDesc(ctx context.Context, arg ListResourcesByVersionAfterDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByVersionAfterDesc,
		arg.Kind,
		arg.AnchorValue,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByVersionBeforeAsc = `-- name: ListResourcesByVersionBeforeAsc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (version, id) <
      (?2, CAST(?3 AS TEXT))
ORDER BY version DESC, id DESC
    LIMIT ?4
`

type ListResourcesByVersionBeforeAscParams struct {
	Kind        string `json:"kind"`
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByVersionBeforeAsc(ctx context.Context, arg ListResourcesByVersionBeforeAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByVersionBeforeAsc,
		arg.Kind,
		arg.AnchorValue,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByVersionBeforeDesc = `-- name: ListResourcesByVersionBeforeDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
  AND (version, id) >
      (?2, CAST(?3 AS TEXT))
ORDER BY version ASC, id ASC
    LIMIT ?4
`

type ListResourcesByVersionBeforeDescParams struct {
	Kind        string `json:"kind"`
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByVersionBeforeDesc(ctx context.Context, arg ListResourcesByVersionBeforeDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByVersionBeforeDesc,
		arg.Kind,
		arg.AnchorValue,
		arg.AnchorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByVersionFirstAsc = `-- name: ListResourcesByVersionFirstAsc :many

SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY version ASC, id ASC
    LIMIT ?2
`

type ListResourcesByVersionFirstAscParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

// ============================================================================
// First page: Version
// ============================================================================
func (q *Queries) ListResourcesByVersionFirstAsc(ctx context.Context, arg ListResourcesByVersionFirstAscParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByVersionFirstAsc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByVersionFirstDesc = `-- name: ListResourcesByVersionFirstDesc :many
SELECT
    id,
    kind,
    version,
    name,
    description,
    spec,
    created_at,
    updated_at
FROM resources
WHERE kind = ?1
ORDER BY version DESC, id DESC
    LIMIT ?2
`

type ListResourcesByVersionFirstDescParams struct {
	Kind      string `json:"kind"`
	PageLimit int64  `json:"page_limit"`
}

func (q *Queries) ListResourcesByVersionFirstDesc(ctx context.Context, arg ListResourcesByVersionFirstDescParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByVersionFirstDesc, arg.Kind, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
