// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_suite_executions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTestSuiteExecution = `-- name: CreateTestSuiteExecution :one

INSERT INTO test_suite_executions (
    id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_suite_id,
    test_suite_name,
    summary
)
VALUES (
           ?1,
           ?2,
           ?3,
           ?4,
           ?5,
           ?6,
           ?7,
           ?8,
           ?9
       )
    RETURNING
    id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_suite_id,
    test_suite_name,
    summary
`

type CreateTestSuiteExecutionParams struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// CRUD
// ============================================================================
func (q *Queries) CreateTestSuiteExecution(ctx context.Context, arg CreateTestSuiteExecutionParams) (TestSuiteExecution, error) {
	row := q.db.QueryRowContext(ctx, createTestSuiteExecution,
		arg.ID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.EnvironmentID,
		arg.EnvironmentName,
		arg.TestSuiteID,
		arg.TestSuiteName,
		arg.Summary,
	)
	var i TestSuiteExecution
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.EnvironmentID,
		&i.EnvironmentName,
		&i.TestSuiteID,
		&i.TestSuiteName,
		&i.Summary,
	)
	return i, err
}

const deleteTestSuiteExecution = `-- name: DeleteTestSuiteExecution :one
DELETE FROM test_suite_executions
WHERE id = ?1
    RETURNING
    id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_suite_id,
    test_suite_name,
    summary
`

func (q *Queries) DeleteTestSuiteExecution(ctx context.Context, id string) (TestSuiteExecution, error) {
	row := q.db.QueryRowContext(ctx, deleteTestSuiteExecution, id)
	var i TestSuiteExecution
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.EnvironmentID,
		&i.EnvironmentName,
		&i.TestSuiteID,
		&i.TestSuiteName,
		&i.Summary,
	)
	return i, err
}

const getTestSuiteExecution = `-- name: GetTestSuiteExecution :one
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE tse.id = ?1
`

type GetTestSuiteExecutionRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) GetTestSuiteExecution(ctx context.Context, id string) (GetTestSuiteExecutionRow, error) {
	row := q.db.QueryRowContext(ctx, getTestSuiteExecution, id)
	var i GetTestSuiteExecutionRow
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.EnvironmentID,
		&i.EnvironmentName,
		&i.TestSuiteID,
		&i.TestSuiteName,
		&i.TestsCount,
		&i.Summary,
	)
	return i, err
}

const getTestSuiteExecutionIDsByID = `-- name: GetTestSuiteExecutionIDsByID :many

SELECT id
FROM test_suite_executions
WHERE id LIKE ?1 || '%'
ORDER BY id ASC
`

// ============================================================================
// Prefix lookup
// ============================================================================
func (q *Queries) GetTestSuiteExecutionIDsByID(ctx context.Context, prefix sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTestSuiteExecutionIDsByID, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestSuiteExecutionIDsByTestSuiteID = `-- name: GetTestSuiteExecutionIDsByTestSuiteID :many
SELECT id
FROM test_suite_executions
WHERE test_suite_id LIKE ?1 || '%'
ORDER BY test_suite_id ASC, id ASC
`

func (q *Queries) GetTestSuiteExecutionIDsByTestSuiteID(ctx context.Context, prefix sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTestSuiteExecutionIDsByTestSuiteID, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestSuiteExecutionStatus = `-- name: GetTestSuiteExecutionStatus :one

SELECT status
FROM test_suite_executions
WHERE id = ?1
`

// ============================================================================
// Status
// ============================================================================
func (q *Queries) GetTestSuiteExecutionStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTestSuiteExecutionStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listTestSuiteExecutionsByFinishedAtAfterAsc = `-- name: ListTestSuiteExecutionsByFinishedAtAfterAsc :many

SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.finished_at, tse.id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.finished_at ASC, tse.id ASC
    LIMIT ?3
`

type ListTestSuiteExecutionsByFinishedAtAfterAscParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

type ListTestSuiteExecutionsByFinishedAtAfterAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// Cursor page: FinishedAt
// ============================================================================
func (q *Queries) ListTestSuiteExecutionsByFinishedAtAfterAsc(ctx context.Context, arg ListTestSuiteExecutionsByFinishedAtAfterAscParams) ([]ListTestSuiteExecutionsByFinishedAtAfterAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByFinishedAtAfterAsc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByFinishedAtAfterAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByFinishedAtAfterAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByFinishedAtAfterDesc = `-- name: ListTestSuiteExecutionsByFinishedAtAfterDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.finished_at, tse.id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.finished_at DESC, tse.id DESC
    LIMIT ?3
`

type ListTestSuiteExecutionsByFinishedAtAfterDescParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

type ListTestSuiteExecutionsByFinishedAtAfterDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByFinishedAtAfterDesc(ctx context.Context, arg ListTestSuiteExecutionsByFinishedAtAfterDescParams) ([]ListTestSuiteExecutionsByFinishedAtAfterDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByFinishedAtAfterDesc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByFinishedAtAfterDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByFinishedAtAfterDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByFinishedAtBeforeAsc = `-- name: ListTestSuiteExecutionsByFinishedAtBeforeAsc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.finished_at, tse.id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.finished_at DESC, tse.id DESC
    LIMIT ?3
`

type ListTestSuiteExecutionsByFinishedAtBeforeAscParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

type ListTestSuiteExecutionsByFinishedAtBeforeAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByFinishedAtBeforeAsc(ctx context.Context, arg ListTestSuiteExecutionsByFinishedAtBeforeAscParams) ([]ListTestSuiteExecutionsByFinishedAtBeforeAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByFinishedAtBeforeAsc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByFinishedAtBeforeAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByFinishedAtBeforeAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByFinishedAtBeforeDesc = `-- name: ListTestSuiteExecutionsByFinishedAtBeforeDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.finished_at, tse.id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.finished_at ASC, tse.id ASC
    LIMIT ?3
`

type ListTestSuiteExecutionsByFinishedAtBeforeDescParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

type ListTestSuiteExecutionsByFinishedAtBeforeDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByFinishedAtBeforeDesc(ctx context.Context, arg ListTestSuiteExecutionsByFinishedAtBeforeDescParams) ([]ListTestSuiteExecutionsByFinishedAtBeforeDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByFinishedAtBeforeDesc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByFinishedAtBeforeDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByFinishedAtBeforeDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByFinishedAtFirstAsc = `-- name: ListTestSuiteExecutionsByFinishedAtFirstAsc :many

SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
ORDER BY tse.finished_at ASC, tse.id ASC
    LIMIT ?1
`

type ListTestSuiteExecutionsByFinishedAtFirstAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// First page: FinishedAt
// ============================================================================
func (q *Queries) ListTestSuiteExecutionsByFinishedAtFirstAsc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByFinishedAtFirstAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByFinishedAtFirstAsc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByFinishedAtFirstAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByFinishedAtFirstAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByFinishedAtFirstDesc = `-- name: ListTestSuiteExecutionsByFinishedAtFirstDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
ORDER BY tse.finished_at DESC, tse.id DESC
    LIMIT ?1
`

type ListTestSuiteExecutionsByFinishedAtFirstDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByFinishedAtFirstDesc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByFinishedAtFirstDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByFinishedAtFirstDesc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByFinishedAtFirstDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByFinishedAtFirstDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByIDAfterAsc = `-- name: ListTestSuiteExecutionsByIDAfterAsc :many

SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE tse.id > CAST(?1 AS TEXT)
ORDER BY tse.id ASC
    LIMIT ?2
`

type ListTestSuiteExecutionsByIDAfterAscParams struct {
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

type ListTestSuiteExecutionsByIDAfterAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// Cursor page: ID
// ============================================================================
func (q *Queries) ListTestSuiteExecutionsByIDAfterAsc(ctx context.Context, arg ListTestSuiteExecutionsByIDAfterAscParams) ([]ListTestSuiteExecutionsByIDAfterAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByIDAfterAsc, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByIDAfterAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByIDAfterAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByIDAfterDesc = `-- name: ListTestSuiteExecutionsByIDAfterDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE tse.id < CAST(?1 AS TEXT)
ORDER BY tse.id DESC
    LIMIT ?2
`

type ListTestSuiteExecutionsByIDAfterDescParams struct {
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

type ListTestSuiteExecutionsByIDAfterDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByIDAfterDesc(ctx context.Context, arg ListTestSuiteExecutionsByIDAfterDescParams) ([]ListTestSuiteExecutionsByIDAfterDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByIDAfterDesc, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByIDAfterDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByIDAfterDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByIDBeforeAsc = `-- name: ListTestSuiteExecutionsByIDBeforeAsc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE tse.id < CAST(?1 AS TEXT)
ORDER BY tse.id DESC
    LIMIT ?2
`

type ListTestSuiteExecutionsByIDBeforeAscParams struct {
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

type ListTestSuiteExecutionsByIDBeforeAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByIDBeforeAsc(ctx context.Context, arg ListTestSuiteExecutionsByIDBeforeAscParams) ([]ListTestSuiteExecutionsByIDBeforeAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByIDBeforeAsc, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByIDBeforeAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByIDBeforeAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByIDBeforeDesc = `-- name: ListTestSuiteExecutionsByIDBeforeDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE tse.id > CAST(?1 AS TEXT)
ORDER BY tse.id ASC
    LIMIT ?2
`

type ListTestSuiteExecutionsByIDBeforeDescParams struct {
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

type ListTestSuiteExecutionsByIDBeforeDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByIDBeforeDesc(ctx context.Context, arg ListTestSuiteExecutionsByIDBeforeDescParams) ([]ListTestSuiteExecutionsByIDBeforeDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByIDBeforeDesc, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByIDBeforeDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByIDBeforeDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByIDFirstAsc = `-- name: ListTestSuiteExecutionsByIDFirstAsc :many

SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
ORDER BY tse.id ASC
    LIMIT ?1
`

type ListTestSuiteExecutionsByIDFirstAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// First page: ID
// ============================================================================
func (q *Queries) ListTestSuiteExecutionsByIDFirstAsc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByIDFirstAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByIDFirstAsc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByIDFirstAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByIDFirstAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByIDFirstDesc = `-- name: ListTestSuiteExecutionsByIDFirstDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
ORDER BY tse.id DESC
    LIMIT ?1
`

type ListTestSuiteExecutionsByIDFirstDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByIDFirstDesc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByIDFirstDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByIDFirstDesc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByIDFirstDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByIDFirstDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStartedAtAfterAsc = `-- name: ListTestSuiteExecutionsByStartedAtAfterAsc :many

SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.started_at, tse.id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.started_at ASC, tse.id ASC
    LIMIT ?3
`

type ListTestSuiteExecutionsByStartedAtAfterAscParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

type ListTestSuiteExecutionsByStartedAtAfterAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// Cursor page: StartedAt
// ============================================================================
func (q *Queries) ListTestSuiteExecutionsByStartedAtAfterAsc(ctx context.Context, arg ListTestSuiteExecutionsByStartedAtAfterAscParams) ([]ListTestSuiteExecutionsByStartedAtAfterAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStartedAtAfterAsc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStartedAtAfterAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStartedAtAfterAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStartedAtAfterDesc = `-- name: ListTestSuiteExecutionsByStartedAtAfterDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.started_at, tse.id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.started_at DESC, tse.id DESC
    LIMIT ?3
`

type ListTestSuiteExecutionsByStartedAtAfterDescParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

type ListTestSuiteExecutionsByStartedAtAfterDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByStartedAtAfterDesc(ctx context.Context, arg ListTestSuiteExecutionsByStartedAtAfterDescParams) ([]ListTestSuiteExecutionsByStartedAtAfterDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStartedAtAfterDesc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStartedAtAfterDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStartedAtAfterDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStartedAtBeforeAsc = `-- name: ListTestSuiteExecutionsByStartedAtBeforeAsc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.started_at, tse.id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.started_at DESC, tse.id DESC
    LIMIT ?3
`

type ListTestSuiteExecutionsByStartedAtBeforeAscParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

type ListTestSuiteExecutionsByStartedAtBeforeAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByStartedAtBeforeAsc(ctx context.Context, arg ListTestSuiteExecutionsByStartedAtBeforeAscParams) ([]ListTestSuiteExecutionsByStartedAtBeforeAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStartedAtBeforeAsc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStartedAtBeforeAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStartedAtBeforeAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStartedAtBeforeDesc = `-- name: ListTestSuiteExecutionsByStartedAtBeforeDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.started_at, tse.id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.started_at ASC, tse.id ASC
    LIMIT ?3
`

type ListTestSuiteExecutionsByStartedAtBeforeDescParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

type ListTestSuiteExecutionsByStartedAtBeforeDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByStartedAtBeforeDesc(ctx context.Context, arg ListTestSuiteExecutionsByStartedAtBeforeDescParams) ([]ListTestSuiteExecutionsByStartedAtBeforeDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStartedAtBeforeDesc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStartedAtBeforeDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStartedAtBeforeDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStartedAtFirstAsc = `-- name: ListTestSuiteExecutionsByStartedAtFirstAsc :many

SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
ORDER BY tse.started_at ASC, tse.id ASC
    LIMIT ?1
`

type ListTestSuiteExecutionsByStartedAtFirstAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// First page: StartedAt
// ============================================================================
func (q *Queries) ListTestSuiteExecutionsByStartedAtFirstAsc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByStartedAtFirstAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStartedAtFirstAsc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStartedAtFirstAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStartedAtFirstAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStartedAtFirstDesc = `-- name: ListTestSuiteExecutionsByStartedAtFirstDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
ORDER BY tse.started_at DESC, tse.id DESC
    LIMIT ?1
`

type ListTestSuiteExecutionsByStartedAtFirstDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByStartedAtFirstDesc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByStartedAtFirstDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStartedAtFirstDesc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStartedAtFirstDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStartedAtFirstDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStatusAfterAsc = `-- name: ListTestSuiteExecutionsByStatusAfterAsc :many

SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.status, tse.id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.status ASC, tse.id ASC
    LIMIT ?3
`

type ListTestSuiteExecutionsByStatusAfterAscParams struct {
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

type ListTestSuiteExecutionsByStatusAfterAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// Cursor page: Status
// ============================================================================
func (q *Queries) ListTestSuiteExecutionsByStatusAfterAsc(ctx context.Context, arg ListTestSuiteExecutionsByStatusAfterAscParams) ([]ListTestSuiteExecutionsByStatusAfterAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStatusAfterAsc, arg.AnchorValue, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStatusAfterAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStatusAfterAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStatusAfterDesc = `-- name: ListTestSuiteExecutionsByStatusAfterDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.status, tse.id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.status DESC, tse.id DESC
    LIMIT ?3
`

type ListTestSuiteExecutionsByStatusAfterDescParams struct {
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

type ListTestSuiteExecutionsByStatusAfterDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByStatusAfterDesc(ctx context.Context, arg ListTestSuiteExecutionsByStatusAfterDescParams) ([]ListTestSuiteExecutionsByStatusAfterDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStatusAfterDesc, arg.AnchorValue, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStatusAfterDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStatusAfterDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStatusBeforeAsc = `-- name: ListTestSuiteExecutionsByStatusBeforeAsc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.status, tse.id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.status DESC, tse.id DESC
    LIMIT ?3
`

type ListTestSuiteExecutionsByStatusBeforeAscParams struct {
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

type ListTestSuiteExecutionsByStatusBeforeAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByStatusBeforeAsc(ctx context.Context, arg ListTestSuiteExecutionsByStatusBeforeAscParams) ([]ListTestSuiteExecutionsByStatusBeforeAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStatusBeforeAsc, arg.AnchorValue, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStatusBeforeAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStatusBeforeAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStatusBeforeDesc = `-- name: ListTestSuiteExecutionsByStatusBeforeDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
WHERE (tse.status, tse.id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY tse.status ASC, tse.id ASC
    LIMIT ?3
`

type ListTestSuiteExecutionsByStatusBeforeDescParams struct {
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

type ListTestSuiteExecutionsByStatusBeforeDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByStatusBeforeDesc(ctx context.Context, arg ListTestSuiteExecutionsByStatusBeforeDescParams) ([]ListTestSuiteExecutionsByStatusBeforeDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStatusBeforeDesc, arg.AnchorValue, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStatusBeforeDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStatusBeforeDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStatusFirstAsc = `-- name: ListTestSuiteExecutionsByStatusFirstAsc :many

SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
ORDER BY tse.status ASC, tse.id ASC
    LIMIT ?1
`

type ListTestSuiteExecutionsByStatusFirstAscRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

// ============================================================================
// First page: Status
// ============================================================================
func (q *Queries) ListTestSuiteExecutionsByStatusFirstAsc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByStatusFirstAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStatusFirstAsc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStatusFirstAscRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStatusFirstAscRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestSuiteExecutionsByStatusFirstDesc = `-- name: ListTestSuiteExecutionsByStatusFirstDesc :many
SELECT
    tse.id,
    tse.started_at,
    tse.finished_at,
    tse.status,
    tse.environment_id,
    tse.environment_name,
    tse.test_suite_id,
    tse.test_suite_name,
    (
        SELECT COUNT(*)
        FROM test_executions te
        WHERE te.test_suite_execution_id = tse.id
    ) AS tests_count,
    tse.summary
FROM test_suite_executions tse
ORDER BY tse.status DESC, tse.id DESC
    LIMIT ?1
`

type ListTestSuiteExecutionsByStatusFirstDescRow struct {
	ID              string    `json:"id"`
	StartedAt       time.Time `json:"started_at"`
	FinishedAt      time.Time `json:"finished_at"`
	Status          string    `json:"status"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	TestSuiteID     string    `json:"test_suite_id"`
	TestSuiteName   string    `json:"test_suite_name"`
	TestsCount      int64     `json:"tests_count"`
	Summary         []byte    `json:"summary"`
}

func (q *Queries) ListTestSuiteExecutionsByStatusFirstDesc(ctx context.Context, pageLimit int64) ([]ListTestSuiteExecutionsByStatusFirstDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestSuiteExecutionsByStatusFirstDesc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestSuiteExecutionsByStatusFirstDescRow{}
	for rows.Next() {
		var i ListTestSuiteExecutionsByStatusFirstDescRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestSuiteID,
			&i.TestSuiteName,
			&i.TestsCount,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTestSuiteExecutionCompleted = `-- name: SetTestSuiteExecutionCompleted :one
UPDATE test_suite_executions
SET
    finished_at = ?1,
    status = ?2,
    summary = ?3
WHERE id = ?4
RETURNING id
`

type SetTestSuiteExecutionCompletedParams struct {
	FinishedAt time.Time `json:"finished_at"`
	Status     string    `json:"status"`
	Summary    []byte    `json:"summary"`
	ID         string    `json:"id"`
}

func (q *Queries) SetTestSuiteExecutionCompleted(ctx context.Context, arg SetTestSuiteExecutionCompletedParams) (string, error) {
	row := q.db.QueryRowContext(ctx, setTestSuiteExecutionCompleted,
		arg.FinishedAt,
		arg.Status,
		arg.Summary,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setTestSuiteExecutionRunning = `-- name: SetTestSuiteExecutionRunning :one

UPDATE test_suite_executions
SET
    started_at = ?1,
    status = 'running'
WHERE id = ?2
RETURNING id
`

type SetTestSuiteExecutionRunningParams struct {
	StartedAt time.Time `json:"started_at"`
	ID        string    `json:"id"`
}

// ============================================================================
// State transitions
// ============================================================================
func (q *Queries) SetTestSuiteExecutionRunning(ctx context.Context, arg SetTestSuiteExecutionRunningParams) (string, error) {
	row := q.db.QueryRowContext(ctx, setTestSuiteExecutionRunning, arg.StartedAt, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}
