// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_tags.sql

package db

import (
	"context"
)

const createTestTag = `-- name: CreateTestTag :exec
INSERT INTO test_tags (
    test_id,
    tag
)
VALUES (
           ?1,
           ?2
       )
`

type CreateTestTagParams struct {
	TestID string `json:"test_id"`
	Tag    string `json:"tag"`
}

func (q *Queries) CreateTestTag(ctx context.Context, arg CreateTestTagParams) error {
	_, err := q.db.ExecContext(ctx, createTestTag, arg.TestID, arg.Tag)
	return err
}

const deleteTestTagsByTestID = `-- name: DeleteTestTagsByTestID :exec
DELETE FROM test_tags
WHERE test_id = ?1
`

func (q *Queries) DeleteTestTagsByTestID(ctx context.Context, testID string) error {
	_, err := q.db.ExecContext(ctx, deleteTestTagsByTestID, testID)
	return err
}

const getTestsByTag = `-- name: GetTestsByTag :many
SELECT r.id, r.kind, r.version, r.name, r.description, r.spec, r.created_at, r.updated_at
FROM resources r
         JOIN test_tags tt
              ON tt.test_id = r.id
WHERE tt.tag = ?1
  AND r.kind = 'test'
ORDER BY r.id ASC
`

func (q *Queries) GetTestsByTag(ctx context.Context, tag string) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getTestsByTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
