// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_executions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTestExecution = `-- name: CreateTestExecution :one

INSERT INTO test_executions (
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
)
VALUES (
           ?1,
           ?2,
           ?3,
           ?4,
           ?5,
           ?6,
           ?7,
           ?8,
           ?9,
           ?10
       )
    RETURNING
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
`

type CreateTestExecutionParams struct {
	ID                   string         `json:"id"`
	TestSuiteExecutionID sql.NullString `json:"test_suite_execution_id"`
	StartedAt            time.Time      `json:"started_at"`
	FinishedAt           time.Time      `json:"finished_at"`
	Status               string         `json:"status"`
	EnvironmentID        string         `json:"environment_id"`
	EnvironmentName      string         `json:"environment_name"`
	TestID               string         `json:"test_id"`
	TestName             string         `json:"test_name"`
	Summary              []byte         `json:"summary"`
}

// ============================================================================
// CRUD
// ============================================================================
func (q *Queries) CreateTestExecution(ctx context.Context, arg CreateTestExecutionParams) (TestExecution, error) {
	row := q.db.QueryRowContext(ctx, createTestExecution,
		arg.ID,
		arg.TestSuiteExecutionID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.EnvironmentID,
		arg.EnvironmentName,
		arg.TestID,
		arg.TestName,
		arg.Summary,
	)
	var i TestExecution
	err := row.Scan(
		&i.ID,
		&i.TestSuiteExecutionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.EnvironmentID,
		&i.EnvironmentName,
		&i.TestID,
		&i.TestName,
		&i.Summary,
	)
	return i, err
}

const deleteTestExecution = `-- name: DeleteTestExecution :one
DELETE FROM test_executions
WHERE id = ?1
    RETURNING
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
`

func (q *Queries) DeleteTestExecution(ctx context.Context, id string) (TestExecution, error) {
	row := q.db.QueryRowContext(ctx, deleteTestExecution, id)
	var i TestExecution
	err := row.Scan(
		&i.ID,
		&i.TestSuiteExecutionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.EnvironmentID,
		&i.EnvironmentName,
		&i.TestID,
		&i.TestName,
		&i.Summary,
	)
	return i, err
}

const getTestExecution = `-- name: GetTestExecution :one
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE id = ?1
`

func (q *Queries) GetTestExecution(ctx context.Context, id string) (TestExecution, error) {
	row := q.db.QueryRowContext(ctx, getTestExecution, id)
	var i TestExecution
	err := row.Scan(
		&i.ID,
		&i.TestSuiteExecutionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.EnvironmentID,
		&i.EnvironmentName,
		&i.TestID,
		&i.TestName,
		&i.Summary,
	)
	return i, err
}

const getTestExecutionIDsByID = `-- name: GetTestExecutionIDsByID :many

SELECT id
FROM test_executions
WHERE id LIKE ?1 || '%'
ORDER BY id ASC
`

// ============================================================================
// Prefix lookup
// ============================================================================
func (q *Queries) GetTestExecutionIDsByID(ctx context.Context, prefix sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTestExecutionIDsByID, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestExecutionIDsByTestSuiteExecutionID = `-- name: GetTestExecutionIDsByTestSuiteExecutionID :many

SELECT id
FROM test_executions
WHERE test_suite_execution_id = ?1
ORDER BY id ASC
`

// ============================================================================
// Parent lookup
// ============================================================================
func (q *Queries) GetTestExecutionIDsByTestSuiteExecutionID(ctx context.Context, testSuiteExecutionID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTestExecutionIDsByTestSuiteExecutionID, testSuiteExecutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestExecutionStatus = `-- name: GetTestExecutionStatus :one

SELECT status
FROM test_executions
WHERE id = ?1
`

// ============================================================================
// Status
// ============================================================================
func (q *Queries) GetTestExecutionStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTestExecutionStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getTestExecutionsByTestSuiteExecutionID = `-- name: GetTestExecutionsByTestSuiteExecutionID :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE test_suite_execution_id =
      CAST(?1 AS TEXT)
ORDER BY id ASC
`

func (q *Queries) GetTestExecutionsByTestSuiteExecutionID(ctx context.Context, testSuiteExecutionID string) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, getTestExecutionsByTestSuiteExecutionID, testSuiteExecutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByFinishedAtAfterAsc = `-- name: ListTestExecutionsByFinishedAtAfterAsc :many

SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (finished_at, id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY finished_at ASC, id ASC
    LIMIT ?3
`

type ListTestExecutionsByFinishedAtAfterAscParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// ============================================================================
// Cursor page: FinishedAt
// ============================================================================
// PositionAfter + ASC
func (q *Queries) ListTestExecutionsByFinishedAtAfterAsc(ctx context.Context, arg ListTestExecutionsByFinishedAtAfterAscParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByFinishedAtAfterAsc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByFinishedAtAfterDesc = `-- name: ListTestExecutionsByFinishedAtAfterDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (finished_at, id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY finished_at DESC, id DESC
    LIMIT ?3
`

type ListTestExecutionsByFinishedAtAfterDescParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// PositionAfter + DESC
func (q *Queries) ListTestExecutionsByFinishedAtAfterDesc(ctx context.Context, arg ListTestExecutionsByFinishedAtAfterDescParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByFinishedAtAfterDesc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByFinishedAtBeforeAsc = `-- name: ListTestExecutionsByFinishedAtBeforeAsc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (finished_at, id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY finished_at DESC, id DESC
    LIMIT ?3
`

type ListTestExecutionsByFinishedAtBeforeAscParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// PositionBefore + ASC
// Results are queried in reverse order.
// The repository must restore ASC order.
func (q *Queries) ListTestExecutionsByFinishedAtBeforeAsc(ctx context.Context, arg ListTestExecutionsByFinishedAtBeforeAscParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByFinishedAtBeforeAsc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByFinishedAtBeforeDesc = `-- name: ListTestExecutionsByFinishedAtBeforeDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (finished_at, id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY finished_at ASC, id ASC
    LIMIT ?3
`

type ListTestExecutionsByFinishedAtBeforeDescParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// PositionBefore + DESC
// Results are queried in reverse order.
// The repository must restore DESC order.
func (q *Queries) ListTestExecutionsByFinishedAtBeforeDesc(ctx context.Context, arg ListTestExecutionsByFinishedAtBeforeDescParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByFinishedAtBeforeDesc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByFinishedAtFirstAsc = `-- name: ListTestExecutionsByFinishedAtFirstAsc :many

SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
ORDER BY finished_at ASC, id ASC
    LIMIT ?1
`

// ============================================================================
// First page: FinishedAt
// ============================================================================
func (q *Queries) ListTestExecutionsByFinishedAtFirstAsc(ctx context.Context, pageLimit int64) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByFinishedAtFirstAsc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByFinishedAtFirstDesc = `-- name: ListTestExecutionsByFinishedAtFirstDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
ORDER BY finished_at DESC, id DESC
    LIMIT ?1
`

func (q *Queries) ListTestExecutionsByFinishedAtFirstDesc(ctx context.Context, pageLimit int64) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByFinishedAtFirstDesc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByIDAfterAsc = `-- name: ListTestExecutionsByIDAfterAsc :many

SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE id > CAST(?1 AS TEXT)
ORDER BY id ASC
    LIMIT ?2
`

type ListTestExecutionsByIDAfterAscParams struct {
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

// ============================================================================
// Cursor page: ID
// ============================================================================
// PositionAfter + ASC
func (q *Queries) ListTestExecutionsByIDAfterAsc(ctx context.Context, arg ListTestExecutionsByIDAfterAscParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByIDAfterAsc, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByIDAfterDesc = `-- name: ListTestExecutionsByIDAfterDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE id < CAST(?1 AS TEXT)
ORDER BY id DESC
    LIMIT ?2
`

type ListTestExecutionsByIDAfterDescParams struct {
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

// PositionAfter + DESC
func (q *Queries) ListTestExecutionsByIDAfterDesc(ctx context.Context, arg ListTestExecutionsByIDAfterDescParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByIDAfterDesc, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByIDBeforeAsc = `-- name: ListTestExecutionsByIDBeforeAsc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE id < CAST(?1 AS TEXT)
ORDER BY id DESC
    LIMIT ?2
`

type ListTestExecutionsByIDBeforeAscParams struct {
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

// PositionBefore + ASC
// Results are queried in reverse order.
// The repository must restore ASC order.
func (q *Queries) ListTestExecutionsByIDBeforeAsc(ctx context.Context, arg ListTestExecutionsByIDBeforeAscParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByIDBeforeAsc, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByIDBeforeDesc = `-- name: ListTestExecutionsByIDBeforeDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE id > CAST(?1 AS TEXT)
ORDER BY id ASC
    LIMIT ?2
`

type ListTestExecutionsByIDBeforeDescParams struct {
	AnchorID  string `json:"anchor_id"`
	PageLimit int64  `json:"page_limit"`
}

// PositionBefore + DESC
// Results are queried in reverse order.
// The repository must restore DESC order.
func (q *Queries) ListTestExecutionsByIDBeforeDesc(ctx context.Context, arg ListTestExecutionsByIDBeforeDescParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByIDBeforeDesc, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByIDFirstAsc = `-- name: ListTestExecutionsByIDFirstAsc :many

SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
ORDER BY id ASC
    LIMIT ?1
`

// ============================================================================
// First page: ID
// ============================================================================
func (q *Queries) ListTestExecutionsByIDFirstAsc(ctx context.Context, pageLimit int64) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByIDFirstAsc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByIDFirstDesc = `-- name: ListTestExecutionsByIDFirstDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
ORDER BY id DESC
    LIMIT ?1
`

func (q *Queries) ListTestExecutionsByIDFirstDesc(ctx context.Context, pageLimit int64) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByIDFirstDesc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStartedAtAfterAsc = `-- name: ListTestExecutionsByStartedAtAfterAsc :many

SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (started_at, id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY started_at ASC, id ASC
    LIMIT ?3
`

type ListTestExecutionsByStartedAtAfterAscParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// ============================================================================
// Cursor page: StartedAt
// ============================================================================
// PositionAfter + ASC
func (q *Queries) ListTestExecutionsByStartedAtAfterAsc(ctx context.Context, arg ListTestExecutionsByStartedAtAfterAscParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStartedAtAfterAsc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStartedAtAfterDesc = `-- name: ListTestExecutionsByStartedAtAfterDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (started_at, id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY started_at DESC, id DESC
    LIMIT ?3
`

type ListTestExecutionsByStartedAtAfterDescParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// PositionAfter + DESC
func (q *Queries) ListTestExecutionsByStartedAtAfterDesc(ctx context.Context, arg ListTestExecutionsByStartedAtAfterDescParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStartedAtAfterDesc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStartedAtBeforeAsc = `-- name: ListTestExecutionsByStartedAtBeforeAsc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (started_at, id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY started_at DESC, id DESC
    LIMIT ?3
`

type ListTestExecutionsByStartedAtBeforeAscParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// PositionBefore + ASC
// Results are queried in reverse order.
// The repository must restore ASC order.
func (q *Queries) ListTestExecutionsByStartedAtBeforeAsc(ctx context.Context, arg ListTestExecutionsByStartedAtBeforeAscParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStartedAtBeforeAsc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStartedAtBeforeDesc = `-- name: ListTestExecutionsByStartedAtBeforeDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (started_at, id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY started_at ASC, id ASC
    LIMIT ?3
`

type ListTestExecutionsByStartedAtBeforeDescParams struct {
	AnchorTimestamp time.Time `json:"anchor_timestamp"`
	AnchorID        string    `json:"anchor_id"`
	PageLimit       int64     `json:"page_limit"`
}

// PositionBefore + DESC
// Results are queried in reverse order.
// The repository must restore DESC order.
func (q *Queries) ListTestExecutionsByStartedAtBeforeDesc(ctx context.Context, arg ListTestExecutionsByStartedAtBeforeDescParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStartedAtBeforeDesc, arg.AnchorTimestamp, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStartedAtFirstAsc = `-- name: ListTestExecutionsByStartedAtFirstAsc :many

SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
ORDER BY started_at ASC, id ASC
    LIMIT ?1
`

// ============================================================================
// First page: StartedAt
// ============================================================================
func (q *Queries) ListTestExecutionsByStartedAtFirstAsc(ctx context.Context, pageLimit int64) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStartedAtFirstAsc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStartedAtFirstDesc = `-- name: ListTestExecutionsByStartedAtFirstDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
ORDER BY started_at DESC, id DESC
    LIMIT ?1
`

func (q *Queries) ListTestExecutionsByStartedAtFirstDesc(ctx context.Context, pageLimit int64) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStartedAtFirstDesc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStatusAfterAsc = `-- name: ListTestExecutionsByStatusAfterAsc :many

SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (status, id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY status ASC, id ASC
    LIMIT ?3
`

type ListTestExecutionsByStatusAfterAscParams struct {
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

// ============================================================================
// Cursor page: Status
// ============================================================================
// PositionAfter + ASC
func (q *Queries) ListTestExecutionsByStatusAfterAsc(ctx context.Context, arg ListTestExecutionsByStatusAfterAscParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStatusAfterAsc, arg.AnchorValue, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStatusAfterDesc = `-- name: ListTestExecutionsByStatusAfterDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (status, id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY status DESC, id DESC
    LIMIT ?3
`

type ListTestExecutionsByStatusAfterDescParams struct {
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

// PositionAfter + DESC
func (q *Queries) ListTestExecutionsByStatusAfterDesc(ctx context.Context, arg ListTestExecutionsByStatusAfterDescParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStatusAfterDesc, arg.AnchorValue, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStatusBeforeAsc = `-- name: ListTestExecutionsByStatusBeforeAsc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (status, id) <
      (?1, CAST(?2 AS TEXT))
ORDER BY status DESC, id DESC
    LIMIT ?3
`

type ListTestExecutionsByStatusBeforeAscParams struct {
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

// PositionBefore + ASC
// Results are queried in reverse order.
// The repository must restore ASC order.
func (q *Queries) ListTestExecutionsByStatusBeforeAsc(ctx context.Context, arg ListTestExecutionsByStatusBeforeAscParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStatusBeforeAsc, arg.AnchorValue, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStatusBeforeDesc = `-- name: ListTestExecutionsByStatusBeforeDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
WHERE (status, id) >
      (?1, CAST(?2 AS TEXT))
ORDER BY status ASC, id ASC
    LIMIT ?3
`

type ListTestExecutionsByStatusBeforeDescParams struct {
	AnchorValue string `json:"anchor_value"`
	AnchorID    string `json:"anchor_id"`
	PageLimit   int64  `json:"page_limit"`
}

// PositionBefore + DESC
// Results are queried in reverse order.
// The repository must restore DESC order.
func (q *Queries) ListTestExecutionsByStatusBeforeDesc(ctx context.Context, arg ListTestExecutionsByStatusBeforeDescParams) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStatusBeforeDesc, arg.AnchorValue, arg.AnchorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStatusFirstAsc = `-- name: ListTestExecutionsByStatusFirstAsc :many

SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
ORDER BY status ASC, id ASC
    LIMIT ?1
`

// ============================================================================
// First page: Status
// ============================================================================
func (q *Queries) ListTestExecutionsByStatusFirstAsc(ctx context.Context, pageLimit int64) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStatusFirstAsc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestExecutionsByStatusFirstDesc = `-- name: ListTestExecutionsByStatusFirstDesc :many
SELECT
    id,
    test_suite_execution_id,
    started_at,
    finished_at,
    status,
    environment_id,
    environment_name,
    test_id,
    test_name,
    summary
FROM test_executions
ORDER BY status DESC, id DESC
    LIMIT ?1
`

func (q *Queries) ListTestExecutionsByStatusFirstDesc(ctx context.Context, pageLimit int64) ([]TestExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTestExecutionsByStatusFirstDesc, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestExecution{}
	for rows.Next() {
		var i TestExecution
		if err := rows.Scan(
			&i.ID,
			&i.TestSuiteExecutionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TestID,
			&i.TestName,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTestExecutionCompleted = `-- name: SetTestExecutionCompleted :one
UPDATE test_executions
SET
    finished_at = ?1,
    status = ?2,
    summary = ?3
WHERE id = ?4
RETURNING id
`

type SetTestExecutionCompletedParams struct {
	FinishedAt time.Time `json:"finished_at"`
	Status     string    `json:"status"`
	Summary    []byte    `json:"summary"`
	ID         string    `json:"id"`
}

func (q *Queries) SetTestExecutionCompleted(ctx context.Context, arg SetTestExecutionCompletedParams) (string, error) {
	row := q.db.QueryRowContext(ctx, setTestExecutionCompleted,
		arg.FinishedAt,
		arg.Status,
		arg.Summary,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setTestExecutionRunning = `-- name: SetTestExecutionRunning :one

UPDATE test_executions
SET
    started_at = ?1,
    status = 'running'
WHERE id = ?2
RETURNING id
`

type SetTestExecutionRunningParams struct {
	StartedAt time.Time `json:"started_at"`
	ID        string    `json:"id"`
}

// ============================================================================
// State transitions
// ============================================================================
func (q *Queries) SetTestExecutionRunning(ctx context.Context, arg SetTestExecutionRunningParams) (string, error) {
	row := q.db.QueryRowContext(ctx, setTestExecutionRunning, arg.StartedAt, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}
