// Code generated by go generate; DO NOT EDIT.

package sqlite

import db "github.com/e2engine/repository/sqlite/internal/sqlc"

func normalizeListTestSuiteExecutionsByFinishedAtAfterAsc(values []db.ListTestSuiteExecutionsByFinishedAtAfterAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByFinishedAtAfterDesc(values []db.ListTestSuiteExecutionsByFinishedAtAfterDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByFinishedAtBeforeAsc(values []db.ListTestSuiteExecutionsByFinishedAtBeforeAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByFinishedAtBeforeDesc(values []db.ListTestSuiteExecutionsByFinishedAtBeforeDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByFinishedAtFirstAsc(values []db.ListTestSuiteExecutionsByFinishedAtFirstAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByFinishedAtFirstDesc(values []db.ListTestSuiteExecutionsByFinishedAtFirstDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByIDAfterAsc(values []db.ListTestSuiteExecutionsByIDAfterAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByIDAfterDesc(values []db.ListTestSuiteExecutionsByIDAfterDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByIDBeforeAsc(values []db.ListTestSuiteExecutionsByIDBeforeAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByIDBeforeDesc(values []db.ListTestSuiteExecutionsByIDBeforeDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByIDFirstAsc(values []db.ListTestSuiteExecutionsByIDFirstAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByIDFirstDesc(values []db.ListTestSuiteExecutionsByIDFirstDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStartedAtAfterAsc(values []db.ListTestSuiteExecutionsByStartedAtAfterAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStartedAtAfterDesc(values []db.ListTestSuiteExecutionsByStartedAtAfterDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStartedAtBeforeAsc(values []db.ListTestSuiteExecutionsByStartedAtBeforeAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStartedAtBeforeDesc(values []db.ListTestSuiteExecutionsByStartedAtBeforeDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStartedAtFirstAsc(values []db.ListTestSuiteExecutionsByStartedAtFirstAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStartedAtFirstDesc(values []db.ListTestSuiteExecutionsByStartedAtFirstDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStatusAfterAsc(values []db.ListTestSuiteExecutionsByStatusAfterAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStatusAfterDesc(values []db.ListTestSuiteExecutionsByStatusAfterDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStatusBeforeAsc(values []db.ListTestSuiteExecutionsByStatusBeforeAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStatusBeforeDesc(values []db.ListTestSuiteExecutionsByStatusBeforeDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStatusFirstAsc(values []db.ListTestSuiteExecutionsByStatusFirstAscRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}

func normalizeListTestSuiteExecutionsByStatusFirstDesc(values []db.ListTestSuiteExecutionsByStatusFirstDescRow) []testSuiteExecutionRow {
	result := make([]testSuiteExecutionRow, len(values))

	for i := range values {
		result[i] = testSuiteExecutionRow{
			ID:              values[i].ID,
			StartedAt:       values[i].StartedAt,
			FinishedAt:      values[i].FinishedAt,
			Status:          values[i].Status,
			EnvironmentID:   values[i].EnvironmentID,
			EnvironmentName: values[i].EnvironmentName,
			TestSuiteID:     values[i].TestSuiteID,
			TestSuiteName:   values[i].TestSuiteName,
			TestsCount:      values[i].TestsCount,
			Summary:         values[i].Summary,
		}
	}

	return result
}
