package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	sqlcDir    = "internal/sqlc"
	outputFile = "testsuiteexecution_normalizers.gen.go"
)

var requiredFields = []string{
	"ID",
	"StartedAt",
	"FinishedAt",
	"Status",
	"EnvironmentID",
	"EnvironmentName",
	"TestSuiteID",
	"TestSuiteName",
	"TestsCount",
	"Summary",
}

func main() {
	types, err := findRowTypes()
	if err != nil {
		panic(err)
	}

	source, err := generate(types)
	if err != nil {
		panic(err)
	}

	//nolint:gosec // Generated Go source is intentionally world-readable.
	if err := os.WriteFile(outputFile, source, 0o644); err != nil {
		panic(err)
	}
}

func findRowTypes() ([]string, error) {
	entries, err := os.ReadDir(sqlcDir)
	if err != nil {
		return nil, err
	}

	var result []string

	fset := token.NewFileSet()

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}

		path := filepath.Join(sqlcDir, entry.Name())

		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}

		for _, declaration := range file.Decls {
			genDecl, ok := declaration.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if !isTargetType(typeSpec.Name.Name) {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				if err := validateFields(typeSpec.Name.Name, structType); err != nil {
					return nil, err
				}

				result = append(result, typeSpec.Name.Name)
			}
		}
	}

	sort.Strings(result)

	return result, nil
}

func isTargetType(name string) bool {
	return strings.HasPrefix(name, "ListTestSuiteExecutions") &&
		strings.HasSuffix(name, "Row")
}

func validateFields(
	typeName string,
	structType *ast.StructType,
) error {
	fields := make(map[string]struct{})

	for _, field := range structType.Fields.List {
		for _, name := range field.Names {
			fields[name.Name] = struct{}{}
		}
	}

	for _, required := range requiredFields {
		if _, ok := fields[required]; !ok {
			return fmt.Errorf(
				"%s does not contain required field %s",
				typeName,
				required,
			)
		}
	}

	return nil
}

func generate(types []string) ([]byte, error) {
	var b bytes.Buffer

	b.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	b.WriteString("package sqlite\n\n")
	b.WriteString(
		"import db \"github.com/e2engine/repository/sqlite/internal/sqlc\"\n\n",
	)

	for _, typeName := range types {
		generateList(&b, typeName)
	}

	return format.Source(b.Bytes())
}

func generateList(
	b *bytes.Buffer,
	typeName string,
) {
	functionName := "normalize" + strings.TrimSuffix(typeName, "Row")

	fmt.Fprintf(
		b,
		"func %s(values []db.%s) []testSuiteExecutionRow {\n",
		functionName,
		typeName,
	)

	b.WriteString("\tresult := make([]testSuiteExecutionRow, len(values))\n\n")
	b.WriteString("\tfor i := range values {\n")
	b.WriteString("\t\tresult[i] = testSuiteExecutionRow{\n")

	for _, field := range requiredFields {
		fmt.Fprintf(
			b,
			"\t\t\t%s: values[i].%s,\n",
			field,
			field,
		)
	}

	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn result\n")
	b.WriteString("}\n\n")
}
